runtime: python39  # or another supported Python version

entrypoint: gunicorn -b :$PORT app:app  # Command to run your Flask app

env_variables:
  FLASK_ENV: production  # Set to 'development' for local dev purposes

instance_class: F2  # This is the instance class you want to use for scaling

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto  # Automatically routes all other URLs to your Flask app
